---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use latest available version
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=512']
      - id: check-case-conflict
      - id: check-executables-have-shebangs  # Shell
      - id: check-shebang-scripts-are-executable  # Shell
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml  # YAML
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-submodules
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: sort-simple-yaml  # YAML
      - id: trailing-whitespace
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.10.0-2  # Use the latest release of shfmt
    hooks:
      - id: shfmt  # Shell
        args: [-i, '2', -w]
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0  # Spellcheck uses version 0.9.0 installed locally
    hooks:
      - id: shellcheck  # Shell
        args: [--enable, all, -x]
      - id: git-check
      - id: git-dirty
      - id: script-must-have-extension  # Shell
        types: [shell, non-executable]
      - id: script-must-not-have-extension  # Shell
        types: [shell, executable]
      - id: forbid-binary
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint  # Markdown
        args: ["--fix"]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: forbid-crlf
      - id: forbid-tabs
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1  # Latest version from adrien
    hooks:
      - id: yamllint  # YAML
        args: [--format, parsable, --strict]
  - repo: https://github.com/google/yamlfmt
    rev: v0.14.0  # Latest version from Google
    hooks:
      - id: yamlfmt  # YAML
